#This is code for creating the maps of the of emergence of the Chyulu hills. 
#Since Taita hills are older, the emergence of the Chyulu hills is of special interest for speciation in the region.
#The data is forest cover date taken from: 
#It was cropped and rotated in QGIS and then manipulated in R.

#The geo tiff of the study region had to be turned, so that the edges are horizontal and vertical respectively. 
#This means, that the map is no longer geo-referenced, but now it fits the requirements for the model.
#The map was then aggregated to 1 square kilometer cell size, also in QGIS.
#The map of the whole study region was then cropped in QGIS again, to obtain a tif of only the Chyulu hills region. 
#This regional map can then be manipulated to simulate the emergence of the Chyulu hills.
#Since we are interested in forest cover as the niche of Zosterops, we use it as a proxy for elevation, since only higher elevations are forested.
#We start from a rather flat surface (low forest cover overall) and increase this to the current status quo (of forest cover).
#Additionally, we reset the Taita hills to their historic forest cover levels (before anthropogenic influence)
# by adding 20% more forest cover.

library(raster)
library(rgdal)
library(tidyverse)
library(rasterVis)

#The function to convert the rasters to the necessary .map format, written by D.Vedder. Only the data sources were changed.

## Take in the AGC raster and create a GeMM map file
convertMap = function(above_ground_carbon, run_length=simlength, out=map_output_file)
{
  if (typeof(above_ground_carbon) == "character") {
    above_ground_carbon = raster(above_ground_carbon)
  }
  print("Converting to GEMM input format")
  map_text = c("## ZOSTEROPS EXPERIMENT MAP", "",
               "# Timesteps", toString(run_length), "",
               "# Simulation arena - autogenerated by `map_creator.R`",
               "# Source: Townsend et al. 2016 (forest cover data)",
               ##"# Sources: GFCC Multi-Year Global 30 m V001. NASA EOSDIS Land Processes DAAC",
               "", "# <id> <x> <y> <temperature> <agc> [parameters]")
  nrows = nrow(above_ground_carbon)
  ncols = ncol(above_ground_carbon)
  i = 1:(nrows*ncols)
  x = rep(1:ncols, nrows)
  y = rep(1:nrows, each=ncols)
  map_text = c(map_text, paste(i, x, y, "temp=293", #XXX link temp to elevation?
                               paste0("prec=", round(above_ground_carbon[i], 2)),
                               paste0("capacity=", capacity(above_ground_carbon[i])),
                               ifelse(above_ground_carbon[i]>0,"initpop", ""),
                              sep="\t"))
  writeLines(map_text, out)
}


capacity= function(agc_data) {
  cc = floor(100* ((agc_data)/100))*2
  cc = sapply(cc, function(p) ifelse(p>=2, p, ifelse(runif(1)<0.01, 2, 0)))
  return(cc)
}
  

#Map of the whole region
Taita_Chyulu=raster("TaitaChyulu_1sqkm.tif")
par(mfrow=c(1,2))
plot(Taita_Chyulu)

#The following is done to both increase the forest cover in the Taita Hills to reach historic values
#and to flatten the skew between woody areas and savannah so that the woody are invasible.
TH <- raster::select(Taita_Chyulu, draw = TRUE) #draw a rectangle around the TH by hand in the plot window

TH10_2_100 <- TH>2.5 # set minimum value (all above is 1 else 0) CHANGE THIS NUMBER TO INCREASE THE EXTEND OF FOREST IN TH
TH10_2_100 <- TH10_2_100*200 #boost up to a high number (here 200)

#add the mask to the full extent
CHTHmask <- merge(TH10_2_100, Taita_Chyulu)
CHTHmask <- CHTHmask==200
CHTHmask[CHTHmask==1] <- 2
CHTHmask[CHTHmask<1] <- 1

#create expanded TH 
THlarge <- Taita_Chyulu*CHTHmask^1.1  #change the number to increase the skew
THlarge[THlarge >100] <- 100

plot(THlarge) #check whether you like the product

writeRaster(THlarge, "TaitaChyulu_1sqkm_ENLARGED.tif")


#Map of just the Chyuluy hills. Note that the cut-off was arbitrarily chosen and does not represent any political / geological area.
Chyulu=raster("Chyulu_cut.tif")
plot(Chyulu)

#This map will now be flattened step by step 2.5% steps 
#down 2.5% forest cover respectively
low_25=seq(75, 2.5, by= -2.5)
simlength_total=length(low_25)*5000
par(mfrow=c(1,1), mar=c(1, 0, 0, 0))

for (i in 1:length(low_25)){
  reclassmat=matrix(c(low_25[i], 100, low_25[i]), ncol=3, byrow=T)
  Chyulu2=reclassify(Chyulu, reclassmat)
  Chyulu2=merge(Chyulu2, THlarge)
  plot(Chyulu2, axes=F, box=F, legend=F)
  writeRaster(Chyulu2, paste0("Chyulu_", low_25[i]*10, ".tif"), overwrite=T)
  #converting the rasters to .map format. Note that the simulation run time is for one map only. 
  #After the simulation ran for that many steps, it will switch to the next map! 
  #If the maps should be used for different simulation lengths, it is necessary to switch the simlength argument!
  convertMap(Chyulu2, run_length = 5000, out=paste0("Chyulu_", low_25[i]*10, ".map"))
}

