#This is code for creating the maps of the of emergence of the Chyulu hills. 
#Since Taita hills are older, the emergence of the Chyulu hills is of special interest for speciation in the region.
#The data is forest cover date taken from: 
#It was cropped and rotated in QGIS and then manipulated in R.

#The geo tiff of the study region had to be turned, so that the edges are horizontal and vertical respectively. 
#This means, that the map is no longer geo-referenced, but now it fits the requirements for the model.
#The map was then aggregated to 1 square kilometer cell size, also in QGIS.
#The map of the whole study region was then cropped in QGIS again, to obtain a tif of only the Chyulu hills region. 
#This regional map can then be manipulated to simulate the emergence of the Chyulu hills.
#Since we are interested in forest cover as the niche of Zosterops, we use it as a proxy for elevation, since only higher elevations are forested.
#We start from a rather flat surface (low forest cover overall) and increase this to the current status quo (of forest cover).
#Additionally, we reset the Taita hills to their historic forest cover levels (before anthropogenic influence)
# by adding 20% more forest cover.

library(raster)
library(rgdal)
library(tidyverse)
library(rasterVis)

#The function to convert the rasters to the necessary .map format, written by D.Vedder. Only the data sources were changed.

## Take in the AGC raster and create a GeMM map file
convertMap = function(above_ground_carbon, run_length=simlength, out=map_output_file)
{
  if (typeof(above_ground_carbon) == "character") {
    above_ground_carbon = raster(above_ground_carbon)
  }
  print("Converting to GEMM input format")
  map_text = c("## ZOSTEROPS EXPERIMENT MAP", "",
               "# Timesteps", toString(run_length), "",
               "# Simulation arena - autogenerated by `map_creator.R`",
               "# Source: Townsend et al. 2016 (forest cover data)",
               ##"# Sources: GFCC Multi-Year Global 30 m V001. NASA EOSDIS Land Processes DAAC",
               "", "# <id> <x> <y> <temperature> <agc> [parameters]")
  nrows = nrow(above_ground_carbon)
  ncols = ncol(above_ground_carbon)
  i = 1:(nrows*ncols)
  x = rep(1:ncols, nrows)
  y = rep(1:nrows, each=ncols)
  map_text = c(map_text, paste(i, x, y, "temp=293", #XXX link temp to elevation?
                               paste0("prec=", round(above_ground_carbon[i], 2)),
                               paste0("capacity=", capacity(above_ground_carbon[i])),
                               ifelse(above_ground_carbon[i]>0,"initpop", ""),
                              sep="\t"))
  writeLines(map_text, out)
}


capacity= function(agc_data) {
  cc = floor(100* ((agc_data+20)/100))*2
  cc = sapply(cc, function(p) ifelse(p>=2, p, ifelse(runif(1)<0.01, 2, 0)))
  return(cc)
}
  

#Map of the whole region
Taita_Chyulu=raster("TaitaChyulu_1sqkm.tif")
Historic_reclassmat=matrix(c(15, 30, 55, 30, 65, 80, 65, 100, 100), ncol=3, byrow=T)
Historic_Taita= reclassify(Taita_Chyulu, Historic_reclassmat)
plot(Taita_Chyulu)
plot(Historic_Taita)

#Map of just the Chyuluy hills. Note that the cut-off was arbitrarily chosen and does not represent any political / geological area.
Chyulu=raster("Chyulu_cut.tif")
plot(Chyulu)

#This map will now be flattened step by step - in 10%, 5% and 2.5% steps 
#down to 10%, 5% and 2.5% forest cover respectively
#For the simulations, we used the 2.5% steps
low_10=seq(70,10, -10)
low_5=seq(75, 5, by = -5)
low_25=seq(75, 2.5, by= -2.5)
simlength_total=2000
simlength_10=round(simlength_total/length(low_10))
simlength_5=round(simlength_total/length(low_5))
simlength_25=round(simlength_total/length(low_25))
par(mfrow=c(1,1), mar=c(1, 0, 0, 0))
for (i in 1:length(low_10)){
  reclassmat=matrix(c(low_10[i], 100, low_10[i]), ncol=3, byrow=T)
  Chyulu2=reclassify(Chyulu, reclassmat)
  Chyulu2=merge(Chyulu2, Taita_Chyulu)
  plot(Chyulu2, axes=F, box=F, legend=T)
  #writeRaster(Chyulu2, paste0("Chyulu_10_", low_10[i], ".tif"), overwrite=T)
  #convertMap(Chyulu2, run_length = simlength_10, out=paste0("Chyulu_10_", low_10[i], ".map"))
}

for (i in 1:length(low_5)){
  reclassmat=matrix(c(low_5[i], 100, low_5[i]), ncol=3, byrow=T)
  Chyulu2=reclassify(Chyulu, reclassmat)
  Chyulu2=merge(Chyulu2, Taita_Chyulu)
  spplot(Chyulu2, col=terrain.colors(100))
  writeRaster(Chyulu2, paste0("Chyulu_5_", low_5[i], ".tif"), overwrite=T)
  convertMap(Chyulu2, run_length = simlength_10, out=paste0("Chyulu_5_", low_50[i], ".map"))
}

for (i in 1:length(low_25)){
  reclassmat=matrix(c(low_25[i], 100, low_25[i]), ncol=3, byrow=T)
  Chyulu2=reclassify(Chyulu, reclassmat)
  Chyulu2=merge(Chyulu2, Historic_Taita)
  plot(Chyulu2, axes=F, box=F, legend=F)
  writeRaster(Chyulu2, paste0("Chyulu_25_", low_25[i]*10, ".tif"), overwrite=T)
  #converting the rasters to .map format. Note that the simulation run time is for one map only. 
  #After the simulation ran for that many steps, it will switch to the next map! 
  #If the maps should be used for different simulation lengths, it is necessary to switch the simlength argument!
  convertMap(Chyulu2, run_length = simlength_25, out=paste0("Chyulu_25_", low_25[i]*10, ".map"))
}

